steps:

- id: 0. check the root and repo
  name: gcr.io/cloud-builders/docker
  dir: /
  entrypoint: bash
  args:
  - "-c"
  - "pwd && ls -l && ls -l /workspace"

- id: 1. leave a mark under /workspace/test1
  name: gcr.io/cloud-builders/docker
  dir: test1
  entrypoint: bash
  args:
  - "-c"
  - "pwd && ls -l && ls -l /workspace && touch mark"

- id: 2. check the mark
  name: gcr.io/cloud-builders/docker
  dir: test2
  entrypoint: bash
  args:
  - "-c"
  - "pwd && ls -l && ls -l /workspace && ls -l /workspace/test1"
  