steps:

- id: 0. check the root
  name: gcr.io/cloud-builders/docker
  dir: /
  entrypoint: bash
  args:
  - "-c"
  - "pwd && ls -l && ls -l /workspace"

- id: 1. check the repo, leave a mark under /workspace
  name: gcr.io/cloud-builders/docker
  dir: test1
  entrypoint: bash
  args:
  - "-c"
  - "pwd && ls -l && ls -l /workspace && touch /workspace/mark"

- id: 2. check the mark, check the 2nd repo
  name: gcr.io/cloud-builders/docker
  dir: test2
  entrypoint: bash
  args:
  - "-c"
  - "pwd && ls -l && ls -l /workspace && ls -l /workspace/test1"
  